name: LevwortScore
main: NurAzliYT\ScoreHud\ScoreHud
api: 5.0.0
version: 1.0.0
author: NurAzliYT
description: Add fully customizable scoreboards to your server.

virions:
- ScoreFactory
- UpdateNotifier
- ConfigUpdater

permissions:
  ls.command.ls:
    default: true
    description: Allow players to use /levwortscorecommand.
